version: "3.8"

services:
  relay:
    image: ${RELAY_DOCKER_REPO}:${RELAY_DOCKER_VERSION}
    environment:
      RELAY_HOST: github.com
    ports:
      - "${RELAY_LOCAL_BIND_PORT-8080}:8080"
      - "${CODECOV_LOCAL_BIND_PORT-8000}:8000"
      - "${HEALTH_CHECK_PORT-8100}:8100"
