---
apiVersion: v1
kind: Service
metadata:
  annotations:
  {{- range $key, $val := .Values.global.annotations }}
    {{ $key }}: {{ $val | quote }}
  {{- end }}
  {{- range $key, $val := .Values.service.annotations }}
    {{ $key }}: {{ $val | quote }}
  {{- end }}
  name: {{ .Release.Name }}
  labels:
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service }}
    {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  ports:
    - port: {{ .Values.relay.service_port }}
      protocol: TCP
      name: relay
      targetPort: {{ .Values.relay.bind_port }}
    - port: {{ .Values.health_port }}
      protocol: TCP
      name: health
      targetPort: {{ .Values.health_port }}
    {{- if .Values.codecov_relay.enabled }}
    - port: {{ .Values.codecov_relay.service_port }}
      protocol: TCP
      name: codecov-relay
      targetPort: {{ .Values.codecov_relay.bind_port }}
    {{- end }}
  selector:
    app: {{ .Release.Name }}
  type: {{ .Values.service.type }}
