name: Relay CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  build:
    name: Build Relay
    uses: codecov/gha-workflows/.github/workflows/build-app.yml@v1.2.10
    secrets: inherit
    with:
      repo: ${{ vars.CODECOV_INTERNAL_RELAY_IMAGE || 'codecov/relay' }}
      cache_requirements: false

  push:
    name: Push
    needs: [ build ]
    secrets: inherit
    if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/heads/main') && github.repository_owner == 'codecov' }}
    uses: codecov/gha-workflows/.github/workflows/push-env.yml@v1.2.10
    with:
      environment: production
      push_rolling: true
      create_sentry_release: false
      repo: ${{ vars.CODECOV_INTERNAL_RELAY_IMAGE || 'codecov/relay' }}

