name: Create Release

on:
  pull_request:
    branches:
      - main
    types: [closed]

permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  create-release:
    name: Tag Release ${{ github.head_ref }} and Push Docker image to Docker Hub
    if: ${{ github.event.pull_request.merged == true && startsWith(github.head_ref, 'release/') && github.repository_owner == 'codecov' }}
    uses: codecov/gha-workflows/.github/workflows/create-release.yml@v1.2.9
    secrets: inherit

  build:
    name: Build Relay
    if: ${{ github.event.pull_request.merged == true && startsWith(github.head_ref, 'release/') && github.repository_owner == 'codecov' }}
    uses: codecov/gha-workflows/.github/workflows/build-app.yml@v1.2.9
    secrets: inherit
    with:
      repo: ${{ vars.CODECOV_INTERNAL_RELAY_IMAGE || 'codecov/relay' }}
      cache_requirements: false

  push:
    name: Push
    needs: [ build ]
    secrets: inherit
    if: ${{ github.event.pull_request.merged == true && startsWith(github.head_ref, 'release/') && github.repository_owner == 'codecov' }}
    uses: codecov/gha-workflows/.github/workflows/push-env.yml@v1.2.9
    with:
      environment: production
      push_release: true
      cache_requirements: false
      repo: ${{ vars.CODECOV_INTERNAL_RELAY_IMAGE || 'codecov/relay' }}