name: Create Release PR

on:
  workflow_dispatch:
    inputs:
      versionName:
        description: 'Name of version  (ie 23.9.5)'
        required: true

jobs:
  create-release-pr:
    permissions:
      contents: 'write'
    name: Create PR for Release ${{ github.event.inputs.versionName }}
    uses: codecov/gha-workflows/.github/workflows/create-release-pr.yml@v1.2.10
    secrets: inherit
