name: Create Release

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  create-release:
    name: Tag Release ${{ github.head_ref }} and Push Docker image to Docker Hub
    if: ${{ github.event.pull_request.merged == true && startsWith(github.head_ref, 'release/') && github.repository_owner == 'codecov' }}
    uses: codecov/gha-workflows/.github/workflows/create-release.yml@v1.2.7
    secrets: inherit

  push-image:
    needs: [create-release]
    if: ${{ github.event.pull_request.merged == true && startsWith(github.head_ref, 'release/') && github.repository_owner == 'codecov' }}
    uses: codecov/gha-workflows/.github/workflows/self-hosted.yml@v1.2.7
    secrets: inherit
    with:
      push_release: true
      repo: ${{ vars.CODECOV_RELAY_IMAGE || 'codecov/relay' }}
      cache_requirements: false
